### PR TITLE
Feature

### PR DESCRIPTION
**Pull request by Ademola101**
This feature branch deals with the whole structure of the article page. Flexbox, Box model and positioning method were applied and used in designing the structure of the page the page.

### CODE REVIEW

**Comment by soieducation** [comment]
# STATUS: CHANGES REQUIRED 🚦 

🥳  Well done @Ademola101  

### Keep up the efforts 🥳 

Your project looks good and your semantics are not looking bad. However, to make sure you fully understood the lessons, please always make sure that:-

- Your repo looks professional (please refer to previous [lesson here](https://www.education.soiconsulting.com/topic/professional-github-repository/)

- Your commit messages are clear enough, explaining what was done at that stage

- Update your `README.md` file to hold your project details, possibly, the live link.

**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by soieducation** [comment]
# STATUS: CHANGES REQUIRED 🚦 

## Hello @Ademola101 :handshake: :handshake: :handshake: 

:+1: This is good to make it this far, your clone looks similar to the original page and it is really nice, congratulations on the good work you have done so far.
:+1: I liked that you have tried to implement all of the minimal requirements of this project, keep it up, and your project is really almost done.
#### :warning: However we need to make few changes to mark this project approved, don't feel discouraged because of being asked some changes more and more. See the requested change below :point_down: :point_down: :point_down: 
### Note: All of requested changes which are marked as [Required] are mandatory to be implemented in order to get this project approved, others which are marked as [Optional] are nice to have in your project to make it outstanding

# [Required Changes] :warning: 
- [ ] Make sure that the linter files are put in the right way, check this [page](https://github.com/ZeenatLawal/linters-config/tree/master/html-css) for the instructions of how to setup your linter files
- [ ] Make sure that all styling is in the stylesheet, there should be no styling in the html file
- [ ] To make your repository more professional, all of the information on the readme file should be like [this](https://github.com/ZeenatLawal/readme-template), only remove parts that don't apply to this project(e.g. tests, deployment)
- [ ] All icons should be shown on the deployed page
- [ ] The whole header section should be fixed while scrolling, currently only the Space & Cosmos text is fixed.
- [ ] The editor's pick and the footer should look similar to the original page
- [ ] The theory of inflation section is missing its text, only the image is visible
- [ ] Please resolve conflicting files before asking for another review
___
**If you are stuck at any point or have any questions, let us know by leaving a comment here. We will be happy to help**
HAPPY CODING :computer:

**Comment by soieducation** [comment]
Hello @Ademola101 
## :warning:Please ensure there are no conflicting files before requesting for a review

**Comment by Ademola101** [comment]
Okay

**Comment by soieducation** [comment]
## Status: Approved :green_circle: 

### Congratulations @Ademola101  :tada: :clinking_glasses: 

**This project has passed all the mandatory requirements :clap: 
It is therefore approved :heavy_check_mark:**

Thank you for making all the required changes highlighted by the last reviewer.
You can now merge to the default branch.
Do not forget to fill the project completion form.

**_Good luck with your next task._**

* * * 
__Happy Coding :smiley:__

**Comment by Ademola101** [comment]
@soieducation Thank you for the help and guidance.

**Pull request merged**
